### ISSUE TITLE
Nothing Shown In Ubuntu 16.04

### ISSUE THREAD

**Issue by sprankhub** [jichu4n/fish-command-timer#16]
- fish installed via apt-get (`sudo apt-get install fish`)
- standard Ubuntu 16.04
- placed fish command timer under `~/.config/fish/conf.d`
- even after restart, nothing is shown

        ~> fish --version
        fish, version 2.2.0
        ~> ls -al ~/.config/fish/conf.d/
        insgesamt 16
        drwxrwxr-x 2 simon simon 4096 Nov 23 08:27 ./
        drwxr-xr-x 5 simon simon 4096 Nov 23 08:26 ../
        -rw-rw-r-- 1 simon simon 7535 Nov 22 16:50 fish_command_timer.fish

Any idea why it does not show anything? I also tried to put it under `/etc/fish/conf.d`, but this did not work as well.

Thanks a lot!

**Comment by leloup314** [comment]
What works for me is to `source` the `fish_command_timer.fish` in my `~/.config/fish/config.fish` file. I moved the `fish_command_timer.fish` into the `~/.config/fish/` folder and added the following to `config.fish`:

`source ~/.config/fish/fish_command_timer.fish`

If your `fish_command_timer.fish` is located somewhere else, just `source` the absolute path to it in your `config.fish`:

`source /abs/path/to/fish_command_timer.fish`

where `/abs/path/to/` is your absolute path.

Hope it helps.

**Comment by sprankhub** [comment]
Indeed! This seems to work - thanks @leloup314! @jichu4n it would be great if you could update the installation section accordingly :)

**Comment by jichu4n** [comment]
Updated instructions. Thanks!
