### ISSUE TITLE
fish 3.0 math now needs --scale=0

### ISSUE THREAD

**Issue by Konstruktionist** [jichu4n/fish-command-timer#18]
See [fish 3.0 math docs](http://fishshell.com/docs/current/commands.html#math)

With the release of fish 3.0 you need to add `--scale=0` to lines after math on [lines 160-164](https://github.com/jichu4n/fish-command-timer/blob/master/conf.d/fish_command_timer.fish#L160-L164).

`math` is now a builtin which default to floats. `--scale=0` sets it to integers.

Also the redirect char `^` is deprecated. Now `2>`

**Comment by jichu4n** [comment]
Thanks for the suggestions! Fixed in c421c0c and 076bb25 .

**Comment by zkendall** [comment]
You rock.
