### ISSUE TITLE
Suggestion: minimum time

### ISSUE THREAD

**Issue by ChristianMichelsen** [jichu4n/fish-command-timer#24]
Hi and thanks for a great extension! 

Would it be possible to allow for a setting a minimum_timer? Such that it only times (or, well, only shows) commands which took longer than e.g. 5 minutes? 
I do not need timings for all of my file system traversing and so on but whenever a command takes longer than (e.g.) 5 minutes I am interested in it.

Thanks a lot!

Cheers,
Christian

**Comment by jichu4n** [comment]
That's a really neat idea!
