### ISSUE TITLE
allow user-overrides

### ISSUE THREAD

**Issue by danielb2** [jichu4n/fish-command-timer#4]
consider having this script stand-alone with ability of user-overrides.

Example:

```
set fish_command_timer_color cyan
source ~/.config/fish/functions/fish_command_timer.fish
```

Would result in the timer to be cyan. That's so user doesn't have to modify the original code

**Comment by jichu4n** [comment]
As explained in the README, you can put it _after_ the source. But you're right - the script should respect any vars _before_ the source too. Implementing this now.
